# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under aon_demo_test/databricks-resources/*
# and aon_demo_test/bundle.yml with staging environment configs,
# when PRs are merged into the default branch
name: Bundle Deployment for aon-demo-test Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./aon_demo_test

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_STAGING }}
  DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN_STAGING }}

jobs:
  staging:
    concurrency: aon-demo-test-staging-bundle-job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Staging Environment
        id: validate
        run: |
          databricks bundle validate -e staging
      - name: Deploy Bundle to Staging Environment
        id: deploy
        run: |
          databricks bundle deploy -e staging
